### ISSUE TITLE
Two errors on startup

### ISSUE THREAD

**Issue by PibeCaverna** [martineausimon/nvim-xresources#4]
I installed through Lazy.nvim and got this two errors after launching neovim
What could have gone wrong?
____________________________________________________________________
E5113: Error while calling lua chunk: vim/_editor.lua:0: /home/franco/.config/nvim/init.lua..nvim_exec2()
called at /home/franco/.config/nvim/init.lua:0../home/franco/.local/share/nvim/lazy/nvim-xresources/colors
/xresources.lua: Vim(colorscheme):E5113: Error while calling lua chunk: ...e/nvim/lazy/nvim-xresources/lua
/nvim-xresources/init.lua:66: loop or previous error loading module 'nvim-xresources.theme'
stack traceback:
        [C]: in function 'require'
        ...e/nvim/lazy/nvim-xresources/lua/nvim-xresources/init.lua:66: in function 'load'
        ...al/share/nvim/lazy/nvim-xresources/colors/xresources.lua:1: in main chunk
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/franco/.config/nvim/init.lua:4: in main chunk
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/franco/.config/nvim/init.lua:4: in main chunk
------------------------------------------------------------------------------------------------------------------

Failed to run `config` for nvim-xresources

vim/_editor.lua:0: /home/franco/.config/nvim/init.lua..nvim_exec2() called at /home/franco/.config/nvim/in
it.lua:0../home/franco/.local/share/nvim/lazy/nvim-xresources/colors/xresources.lua: Vim(colorscheme):E511
3: Error while calling lua chunk: ...nvim/lazy/nvim-xresources/lua/nvim-xresources/colors.lua:5: attempt t
o index local 'opts' (a nil value)
stack traceback:
^I...nvim/lazy/nvim-xresources/lua/nvim-xresources/colors.lua:5: in main chunk
^I[C]: in function 'require'
^I.../nvim/lazy/nvim-xresources/lua/nvim-xresources/theme.lua:1: in main chunk
^I[C]: in function 'require'
^I...e/nvim/lazy/nvim-xresources/lua/nvim-xresources/init.lua:66: in function 'load'
^I...al/share/nvim/lazy/nvim-xresources/colors/xresources.lua:1: in main chunk
^I[C]: in function 'nvim_exec2'
^Ivim/_editor.lua: in function 'cmd'
^I/home/franco/.config/nvim/lua/PCaverna.lua:45: in function 'config'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:366: in function <...local/share/nvim/lazy/l
azy.nvim/lua/lazy/core/loader.lua:364>
^I[C]: in function 'xpcall'
^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:113: in function 'try'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:381: in function 'config'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:348: in function '_load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:191: in function 'load'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:123: in function 'startup'
^I...ranco/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:110: in function 'setup'
^I/home/franco/.config/nvim/lua/PCaverna.lua:22: in main chunk
^I[C]: in function 'require'
^I/home/franco/.config/nvim/init.lua:2: in main chunk

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - lua/PCaverna.lua:45 _in_ **config**
  - lua/PCaverna.lua:22
  - init.lua:2

**Comment by martineausimon** [comment]
Sorry for this issue ! 
It seems that the plugin is not properly loaded with `lazy.nvim`. Could you share a minimal example of your setup ?

**Comment by martineausimon** [comment]
Hello again, I notice there is an error in my `README.md` : In order for the plugin to work, it is necessary to call the function setup() as follows :

```lua
  {
    'martineausimon/nvim-xresources',
    lazy = false,
    priority = 1000,
    config = function()
      require('nvim-xresources').setup() -- required
      vim.cmd('colorscheme xresources')
    end
  }
```

Sorry for that and thank you for bringing up this issue !

**Comment by PibeCaverna** [comment]
It worked, just pasted the bit of code in the lazy config and voila! Thanks for helping me out <3

> Hello again, I notice there is an error in my `README.md` : In order for the plugin to work, it is necessary to call the function setup() as follows :
> 
> ```lua
>   {
>     'martineausimon/nvim-xresources',
>     lazy = false,
>     priority = 1000,
>     config = function()
>       require('nvim-xresources').setup() -- required
>       vim.cmd('colorscheme xresources')
>     end
>   }
> ```
> 
> Sorry for that and thank you for bringing up this issue !
